apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app-deployment 
  labels:
    env: development
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: nginx
      labels:
        type: backend
    spec:
      containers:
        - name: nginx
          image: nginx
